version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
  heroku: circleci/heroku@1.0.1

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler:2.1.4
      - ruby/bundle-install
      - run: 'bundle exec rspec'
